// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int32            `json:"id"`
	Name              string           `json:"name"`
	PhoneNumber       string           `json:"phone_number"`
	Otp               string           `json:"otp"`
	OtpExpirationTime pgtype.Timestamp `json:"otp_expiration_time"`
}
